#!/usr/bin/env python3
"""
Interactively capture a web page as a scraper test fixture.

Usage:
    python tools/capture.py <url> [options]

Options:
    --venue NAME      Venue name  (injected as seed context, same as VenueSeed)
    --address TEXT    Venue address  (injected as seed context)
    --lat FLOAT       Venue latitude  (injected as seed context)
    --lon FLOAT       Venue longitude  (injected as seed context)
    --from-file PATH  Use a local HTML file instead of fetching the URL
    --ai              Include Claude AI extractor in auto-extraction
    --id SLUG         Override the fixture directory name (auto-generated by default)
    --notes TEXT      Free-text notes describing what this fixture tests

The tool:
  1. Fetches (or reads) the page
  2. Runs the extractor waterfall (JSON-LD → OpenGraph, optionally AI)
  3. Opens $EDITOR so you can review and edit the expected output
  4. Saves tests/fixtures/<id>/  with fixture.json, page.html, and clean_text.txt

The resulting fixture is immediately usable by `pytest` and `tools/export_finetune.py`.
"""
from __future__ import annotations
import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import requests as _req

from scraper.extractors import opengraph, inline_json, dates as dates_extractor
from scraper.extractors.jsonld import extract_all as jsonld_extract_all

FIXTURES_DIR = Path(__file__).parent.parent / 'tests' / 'fixtures'
_UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

_EXPECTED_KEYS = [
    'title', 'description', 'start_datetime', 'end_datetime',
    'location_title', 'location_address', 'location_lat', 'location_lon',
    'ticket_price', 'ticket_url', 'url', 'image_url', 'tag_names',
    'rdates', 'exdates',
]


def _fetch(url: str) -> str:
    resp = _req.get(url, headers={'User-Agent': _UA}, timeout=20, allow_redirects=True)
    resp.raise_for_status()
    return resp.text


def _slug(text: str) -> str:
    text = re.sub(r'[^\w\s-]', '', text.lower())
    text = re.sub(r'[\s_-]+', '-', text).strip('-')
    return text[:60] or 'fixture'


def _auto_extract(html: str, url: str, use_ai: bool, api_key: str) -> list[dict]:
    """
    Run extractors and return a list of event dicts.
    Multi-event pages (multiple JSON-LD events) produce a list with >1 item;
    single-event pages produce a list with 1 item (or 0 on total failure).
    """
    jl_events = jsonld_extract_all(html, url)
    if jl_events:
        print(f"  JSON-LD:   {len(jl_events)} event(s)")
        if len(jl_events) > 1:
            # Multiple events found — no point running OpenGraph/AI
            return jl_events

    result: dict = {}
    if jl_events:
        result = dict(jl_events[0])

    def _merge(base: dict, new: dict) -> int:
        added = 0
        for k, v in new.items():
            if v is None:
                continue
            if k not in base or base[k] is None:
                base[k] = v
                added += 1
            elif k == 'description' and len(str(v)) > len(str(base[k])):
                base[k] = v
        return added

    ij = inline_json.extract(html, url)
    if ij:
        added = _merge(result, ij)
        if added:
            print(f"  Inline JS: +{added} fields")

    og = opengraph.extract(html, url)
    if og:
        added = _merge(result, og)
        if added:
            print(f"  OpenGraph: +{added} fields")

    if use_ai and api_key:
        try:
            from scraper.extractors.ai import extract as ai_extract
            ai = ai_extract(html, url, api_key)
            if ai:
                added = _merge(result, ai)
                if added:
                    print(f"  AI:        +{added} fields")
        except Exception as exc:
            print(f"  AI:        failed ({exc})")
    elif use_ai and not api_key:
        print("  AI:        skipped (ANTHROPIC_API_KEY not set)")

    # ── Dates extractor (rdates / exdates) ────────────────────────────────────
    # Try sources in order: trafilatura clean text, inline JS schedule hint,
    # then description. Stop after the first source that yields results.
    try:
        import trafilatura as _traf
        _clean = _traf.extract(html, include_comments=False, include_tables=False) or ''
    except ImportError:
        _clean = ''
    for text_src in filter(None, [_clean, result.get('_schedule_text'), result.get('description')]):
        date_info = dates_extractor.extract(text_src)
        if not date_info:
            continue
        added = 0
        for k in ('start_datetime', 'end_datetime'):
            if date_info.get(k) and not result.get(k):
                result[k] = date_info[k]
                added += 1
        if date_info.get('rdates'):
            existing = result.get('rdates') or []
            new = [r for r in date_info['rdates'] if r not in existing]
            result['rdates'] = existing + new
            added += len(new)
        if date_info.get('exdates'):
            existing = result.get('exdates') or []
            seen = {e['datetime'] for e in existing}
            new = [e for e in date_info['exdates'] if e['datetime'] not in seen]
            result['exdates'] = existing + new
            added += len(new)
        if added:
            print(f"  Dates:     +{added} fields")
        break  # stop after first source that yields results

    return [result] if result else []


def _open_editor(content: str) -> str:
    editor = os.environ.get('VISUAL') or os.environ.get('EDITOR') or 'nano'
    cmd = [editor]
    # VS Code returns immediately by default; --wait blocks until the tab is closed
    if os.path.basename(editor) in ('code', 'code-insiders'):
        cmd.append('--wait')
    with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
        f.write(content)
        tmp = f.name
    try:
        subprocess.run(cmd + [tmp], check=True)
        return Path(tmp).read_text()
    finally:
        Path(tmp).unlink(missing_ok=True)


def _print_summary(expected: dict) -> None:
    print("\n--- Auto-extracted fields ---")
    for k in _EXPECTED_KEYS:
        v = expected.get(k)
        if v is not None:
            val_str = str(v)
            if len(val_str) > 72:
                val_str = val_str[:69] + '...'
            print(f"  {k:<20} {val_str!r}")
    print()


def main():
    parser = argparse.ArgumentParser(
        description='Capture a web page as a scraper test fixture',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('url', help='URL to capture')
    parser.add_argument('--venue',     default='', metavar='NAME',   help='Venue name (seed context)')
    parser.add_argument('--address',   default='', metavar='TEXT',   help='Venue address (seed context)')
    parser.add_argument('--lat',       type=float, metavar='FLOAT',  help='Latitude (seed context)')
    parser.add_argument('--lon',       type=float, metavar='FLOAT',  help='Longitude (seed context)')
    parser.add_argument('--from-file', metavar='PATH',               help='Read HTML from a local file')
    parser.add_argument('--ai',        action='store_true',          help='Use AI extractor')
    parser.add_argument('--id',        dest='fixture_id', default='',help='Override fixture directory name')
    parser.add_argument('--notes',     default='',                   help='Notes for the fixture')
    args = parser.parse_args()

    api_key = os.getenv('ANTHROPIC_API_KEY', '')

    # ── Fetch / read HTML ─────────────────────────────────────────────────────
    if args.from_file:
        html = Path(args.from_file).read_text()
        print(f"Read {len(html):,} bytes from {args.from_file}")
    else:
        print(f"Fetching {args.url} …")
        try:
            html = _fetch(args.url)
        except Exception as exc:
            print(f"Fetch failed: {exc}", file=sys.stderr)
            sys.exit(1)
        print(f"  {len(html):,} bytes")

    # ── Extract clean text with trafilatura ───────────────────────────────────
    clean_text = None
    try:
        import trafilatura
        clean_text = trafilatura.extract(html, include_comments=False, include_tables=False)
        if clean_text:
            print(f"  trafilatura: {len(clean_text):,} chars of clean text")
    except ImportError:
        pass

    # ── Run extractors ────────────────────────────────────────────────────────
    print("Running extractors …")
    extracted_list = _auto_extract(html, args.url, args.ai, api_key)

    # ── Build seed context ────────────────────────────────────────────────────
    seed_ctx: dict = {}
    if args.venue:
        seed_ctx['location_title'] = args.venue
    if args.address:
        seed_ctx['location_address'] = args.address
    if args.lat is not None:
        seed_ctx['location_lat'] = args.lat
    if args.lon is not None:
        seed_ctx['location_lon'] = args.lon

    # Build expected: merge seed_ctx as fallback into each extracted event
    def _build_expected(ev: dict) -> dict:
        merged = {**seed_ctx, **ev}
        return {k: merged.get(k) for k in _EXPECTED_KEYS}

    multi = len(extracted_list) > 1
    if multi:
        expected = [_build_expected(ev) for ev in extracted_list]
        print(f"\n--- {len(expected)} events found ---")
        for i, ev in enumerate(expected, 1):
            print(f"\n  Event {i}: {ev.get('title', '(no title)')!r}")
            for k in _EXPECTED_KEYS:
                v = ev.get(k)
                if v is not None:
                    val_str = str(v)
                    if len(val_str) > 60:
                        val_str = val_str[:57] + '...'
                    print(f"    {k:<20} {val_str!r}")
    else:
        extracted = extracted_list[0] if extracted_list else {}
        expected = _build_expected(extracted)
        _print_summary(expected)

    # ── Determine fixture ID ──────────────────────────────────────────────────
    first_title = (extracted_list[0].get('title') if extracted_list else '') or ''
    fixture_id = args.fixture_id or _slug(first_title or args.url.split('//')[-1])
    print(f"\nFixture ID: {fixture_id}  (edit --id to override)")

    # ── Build initial fixture.json ────────────────────────────────────────────
    fixture: dict = {'url': args.url}
    if args.notes:
        fixture['notes'] = args.notes
    if seed_ctx:
        fixture['seed_context'] = seed_ctx
    fixture['expected'] = expected  # list if multi-event, dict if single

    # ── Let user review / edit ────────────────────────────────────────────────
    edited = _open_editor(json.dumps(fixture, indent=2, ensure_ascii=False))
    try:
        final = json.loads(edited)
    except json.JSONDecodeError as exc:
        print(f"Invalid JSON after editing: {exc}", file=sys.stderr)
        sys.exit(1)

    # ── Save fixture ──────────────────────────────────────────────────────────
    out_dir = FIXTURES_DIR / fixture_id
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / 'fixture.json').write_text(
        json.dumps(final, indent=2, ensure_ascii=False) + '\n'
    )
    (out_dir / 'page.html').write_text(html)
    if clean_text:
        (out_dir / 'clean_text.txt').write_text(clean_text)

    print(f"\nSaved to {out_dir.relative_to(Path.cwd()) if out_dir.is_relative_to(Path.cwd()) else out_dir}/")
    print(f"  fixture.json   {len(json.dumps(final)):>7,} bytes")
    print(f"  page.html      {len(html):>7,} bytes")
    if clean_text:
        print(f"  clean_text.txt {len(clean_text):>7,} bytes")
    print(f"\nRun tests:  pytest tests/")


if __name__ == '__main__':
    main()
